### ISSUE TITLE
Not working with python3 - TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [SapphireProject/sapphire#2]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sapphire/__main__.py", line 31, in <module>
    bf = run([path+'bfasm'], stdout=PIPE, input=asm, encoding='ascii')
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by maviek** [comment]
The same as in #3, update your python version.
