### ISSUE TITLE
Add more operators to expr.

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [SapphireProject/sapphire#4]
```
var a = 2

assert(a == 2)
```

```
Traceback (most recent call last):
  File "main.py", line 128, in <module>
    e(m(b,a))
  File "main.py", line 109, in main
    parser = Parser(lexer, stack_size)
  File "/mnt/c/users/pc/desktop/bfxt/aa/src/_parser.py", line 20, in __init__
    self.parse()
  File "/mnt/c/users/pc/desktop/bfxt/aa/src/_parser.py", line 306, in parse
    self.parse_token(token)
  File "/mnt/c/users/pc/desktop/bfxt/aa/src/_parser.py", line 275, in parse_token
    s = self.expr(token.value)
  File "/mnt/c/users/pc/desktop/bfxt/aa/src/_parser.py", line 24, in expr
    e = expr(e)
  File "/mnt/c/users/pc/desktop/bfxt/aa/src/expr.py", line 78, in expr
    postfix = infix_to_postfix(s)
  File "/mnt/c/users/pc/desktop/bfxt/aa/src/expr.py", line 51, in infix_to_postfix
    else:  raise ValueError("')' cannot be added to the stack if it is empty")
ValueError: ')' cannot be added to the stack if it is empty
```

We should add `==` support to exprs.

**Comment by maviek** [comment]
more? == works fine, but here lexer detected this as assigning "= 2" into variable "assert(a "

**Comment by KrzysztofSzewczyk** [comment]
So it needs to be fixed, as it's behaving like == operator in expr is unknown
