### ISSUE TITLE
Test 4 fails everytime

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [SapphireProject/sapphire#7]
```ruby
$ python3 sapphire test/test4.py > out.b
warning: strings not supported; using None instead
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sapphire/__main__.py", line 320, in <module>
    ] + sph(code) + [
  File "sapphire/__main__.py", line 94, in sph
    asm += sph(c)
  File "sapphire/__main__.py", line 165, in sph
    builtins.pop()
IndexError: pop from empty list
```

**Comment by maviek** [comment]
```ruby
$ python sapphire test\test4.py >output.py
warning: strings not supported; using None instead

$ bfi16 output.b
38
```
